language: objective-c
osx_image: xcode7.3

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - xcpretty --version

script:
    - xcodebuild -project travis-ci-practice.xcodeproj -scheme travis-ci-practice -destination 'platform=iOS Simulator,name=iPhone 6' clean build | xcpretty
    - xctool -project travis-ci-practice.xcodeproj -scheme travis-ci-practice run-tests  -test-sdk iphonesimulator

notifications:
    email:
      recipients:
        - nickDevUic@gmail.com
      on_success: always
      on_failure: always
